Added testing multiple python version support
mmzeynalli/integrify pull request #14
Opened 2024-10-02 21:31 UTC by mmzeynalli

Fixed:
#7, #11, #12

2024-10-03 04:50 UTC, vahidzhe requested changes

2024-10-03 04:50 UTC, vahidzhe commented on README.md
Actiondaki python testi ucun de badge yerlesdirmek lazim bura

2024-10-07 16:14 UTC, mmzeynalli commented
@ShahriyarR okdusa vurum

2024-10-08 17:26 UTC, ShahriyarR approved these changes
LGTM

2024-10-08 18:39 UTC, merged